// Code generated by Icestudio 0.8.0

`default_nettype none

//---- Top entity
module main (
 input va527ad,
 input v22f8d1,
 input [9:0] vdf932c,
 input vd2f057,
 input vc8d753,
 input v92a92f,
 input v3df3e1,
 input v36b650,
 output v195b8b,
 output v1955dc,
 output vd13f63,
 output v05493a,
 output v879a5c,
 output v24805d,
 output v1eb576,
 output v613efa,
 output [2:0] v82db97,
 output v9ce098,
 output v904e8c,
 output veaa70d
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire w9;
 wire [0:9] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire [0:2] w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 assign w0 = va527ad;
 assign v195b8b = w1;
 assign w2 = vd2f057;
 assign w3 = v22f8d1;
 assign w4 = vc8d753;
 assign w5 = vc8d753;
 assign w9 = v92a92f;
 assign w10 = vdf932c;
 assign w11 = v3df3e1;
 assign w12 = v36b650;
 assign v24805d = w13;
 assign v1955dc = w14;
 assign v05493a = w15;
 assign v9ce098 = w16;
 assign v904e8c = w17;
 assign v613efa = w18;
 assign v82db97 = w19;
 assign vd13f63 = w20;
 assign v879a5c = w21;
 assign v1eb576 = w22;
 assign veaa70d = w23;
 assign w5 = w4;
 main_v69b127 v69b127 (
  .ICE_CS(w0),
  .F_MISO(w1),
  .F_MOSI(w2),
  .F_SCLK(w3),
  .RST(w4),
  .spi_strb(w6),
  .from_spi(w7),
  .to_spi(w8)
 );
 main_vf8ce5e vf8ce5e (
  .RST(w5),
  .spi_strb(w6),
  .from_spi(w7),
  .to_spi(w8),
  .DCLK(w9),
  .ADC_DATA(w10),
  .TOP_T1(w11),
  .TOP_T2(w12),
  .Pdamp(w13),
  .PHV(w14),
  .PnHV(w15),
  .DAC_CS(w16),
  .DAC_MOSI(w17),
  .DAC_SCLK(w18),
  .RGB(w19),
  .HILO(w20),
  .HV_EN(w21),
  .ADC_CLK(w22),
  .EA_CLK(w23)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v69b127 (
 input ICE_CS,
 input F_SCLK,
 input F_MOSI,
 input [7:0] to_spi,
 input RST,
 output F_MISO,
 output [7:0] from_spi,
 output spi_strb
);
 // @include spi_slave.v
  spi_slave spi_uut(
 .rstb(!RST),.ten(1'b1),
 .mlb(1'b1),.ss(ICE_CS),
 .sck(F_SCLK),.sdin(F_MOSI),
 .sdout(F_MISO),.tdata(to_spi),
 .done(spi_strb),.rdata(from_spi));
endmodule

module main_vf8ce5e (
 input RST,
 input DCLK,
 input [9:0] ADC_DATA,
 input TOP_T1,
 input TOP_T2,
 input [7:0] from_spi,
 input spi_strb,
 output PHV,
 output PnHV,
 output Pdamp,
 output HILO,
 output HV_EN,
 output ADC_CLK,
 output DAC_SCLK,
 output DAC_CS,
 output DAC_MOSI,
 output [7:0] to_spi,
 output [2:0] RGB,
 output EA_CLK
);
 // @include adc_dac_pulser.v
 // @include mcp4812.v
 
 adc_dac_pulser pulsar_uut(
  .RST      (RST     ),
  .DCLK     (DCLK    ),
  .ADC_DATA (ADC_DATA),
  .HILO     (HILO    ),
  .HV_EN    (HV_EN   ),
  .TOP_T1   (TOP_T1  ),
  .TOP_T2   (TOP_T2  ),
  .EA_CLK   (EA_CLK  ),
  .PHV      (PHV     ),
  .PnHV     (PnHV    ),
  .Pdamp    (Pdamp   ),
  .ADC_CLK  (ADC_CLK ),
  .DAC_SCLK (DAC_SCLK),
  .DAC_CS   (DAC_CS  ),
  .DAC_MOSI (DAC_MOSI),
  .spi_strb (spi_strb),
  .to_spi   (to_spi  ),
  .from_spi (from_spi),
  .RGB      (RGB     ));
endmodule
