// Code generated by Icestudio 0.8.0

`default_nettype none

//---- Top entity
module main (
 output v841a14
);
 wire w0;
 assign v841a14 = w0;
 main_v2fe9ba v2fe9ba (
  .blink(w0)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v2fe9ba (
 output blink
);
 wire clk48,clk64; // High frequency oscillator
 defparam OSCInst0.CLKHF_DIV = "0b00";
 SB_HFOSC OSCInst0(.CLKHFEN(1'b1), 
 .CLKHFPU(1'b1),.CLKHF(clk48)  //48MHz
 ) /* synthesis ROUTE_THROUGH_FABRIC= [0] */;
 SB_PLL40_CORE pll(.REFERENCECLK(clk48),
 .PLLOUTCORE(clk64),.PLLOUTGLOBAL(),//64MHz
 .RESETB(1'b1),.BYPASS(1'b0),.LOCK(blink));
 //\\ Fin=48, Fout=64;
 defparam pll.DIVR = 4'b0010;
 defparam pll.DIVF = 7'b0111111;
 defparam pll.DIVQ = 3'b100;
 defparam pll.FILTER_RANGE = 3'b001;
 defparam pll.FEEDBACK_PATH = "SIMPLE";
 defparam pll.DELAY_ADJUSTMENT_MODE_FEEDBACK = "FIXED";
 defparam pll.FDA_FEEDBACK = 4'b0000;
 defparam pll.DELAY_ADJUSTMENT_MODE_RELATIVE = "FIXED";
 defparam pll.FDA_RELATIVE = 4'b0000;
 defparam pll.SHIFTREG_DIV_MODE = 2'b00;
 defparam pll.PLLOUT_SELECT = "GENCLK";
 defparam pll.ENABLE_ICEGATE = 1'b0;
 reg [31:0] cnt;
 always@(posedge clk64)begin
  cnt=(cnt==(64000000-1))?0:cnt+1;
  //blink = ~blink;
 end
 
endmodule
