/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.0.64.1
    Soft IP Version: 1.0.0
    Mon Aug 10 23:32:30 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sc_fifo (clk_i, rst_i, wr_en_i, rd_en_i, wr_data_i, full_o, empty_o,
    almost_full_o, almost_empty_o, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  wr_en_i;
    input  rd_en_i;
    input  [15:0]  wr_data_i;
    output  full_o;
    output  empty_o;
    output  almost_full_o;
    output  almost_empty_o;
    output  [15:0]  rd_data_o;
endmodule