#!/bin/bash

# Script to run Yosys synthesis and nextpnr place'n'route

# exit when any command fails
#set -e

# Tools used
SYNTOOL=yosys
PRTOOL=nextpnr-ice40
STATOOL=icetime

# Properties
FREQMHZ=65
DEVICE=up5k
PACKAGE=sg48
TOPNAME=dft
SRCFILES=""

# Parse Verilog sources
VFILES=files.list
IFS=$'\r\n' GLOBIGNORE='*' command eval 'VFILES_ARR=($(cat ${VFILES}))'
for i in "${VFILES_ARR[@]}"
do
    SRCFILES="${SRCFILES} ${i}"
done

# Synthesis
${SYNTOOL} -l syn.rpt -p "synth_ice40 -dsp -top ${TOPNAME} -json ${TOPNAME}.json" ${SRCFILES}

# Place and route
${PRTOOL} --seed 43 -l pr.rpt --freq ${FREQMHZ} --${DEVICE} --package ${PACKAGE} --json ${TOPNAME}.json --asc ${TOPNAME}.asc

# Timing analysis
${STATOOL} -d ${DEVICE} ${TOPNAME}.asc -c ${FREQMHZ} -t -i | tee sta.rpt
