// Code generated by Icestudio 0.8.0

`default_nettype none

//---- Top entity
module main (
 input v18c5db,
 input v8137d8,
 input v6e7da4,
 input v8fbca8,
 input [9:0] v9cfb0f,
 input v16dc94,
 input v8747c7,
 input v06a7a0,
 input v91555a,
 input v67f614,
 input v75b83d,
 input vf0b068,
 output vd49f92,
 output v1c8752,
 output va238f5,
 output vfa2b53,
 output vd337af,
 output vd6dd28,
 output v93932d,
 output v7439f4,
 output v4e8f3c,
 output v11c383,
 output vc95bf7
);
 wire w0;
 wire w1;
 wire [0:9] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 assign w0 = v18c5db;
 assign w1 = v8fbca8;
 assign w2 = v9cfb0f;
 assign w3 = v16dc94;
 assign w4 = v8747c7;
 assign w5 = v06a7a0;
 assign w6 = v91555a;
 assign w7 = v67f614;
 assign w8 = v75b83d;
 assign w9 = vf0b068;
 assign vfa2b53 = w10;
 assign vd337af = w11;
 assign v4e8f3c = w12;
 assign v11c383 = w13;
 assign vd6dd28 = w14;
 assign v93932d = w15;
 assign v7439f4 = w16;
 assign vd49f92 = w17;
 assign v1c8752 = w18;
 assign va238f5 = w19;
 assign w20 = v8137d8;
 assign w21 = v6e7da4;
 assign vc95bf7 = w22;
 main_v30db52 v30db52 (
  .RCLK(w0),
  .DCLK(w1),
  .ADC_DATA(w2),
  .HILO(w3),
  .HV_EN(w4),
  .TOP_T1(w5),
  .TOP_T2(w6),
  .F_SCLK(w7),
  .F_MOSI(w8),
  .ICE_CS(w9),
  .ADC_CLK(w10),
  .DAC_SCLK(w11),
  .Lred(w12),
  .Lgreen(w13),
  .DAC_CS(w14),
  .DAC_MOSI(w15),
  .F_MISO(w16),
  .PHV(w17),
  .PnHV(w18),
  .Pdamp(w19),
  .BT_USER(w20),
  .BT_TRIG(w21),
  .Lblue(w22)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v30db52 (
 input RCLK,
 input BT_USER,
 input BT_TRIG,
 input DCLK,
 input [9:0] ADC_DATA,
 input HILO,
 input HV_EN,
 input TOP_T1,
 input TOP_T2,
 input F_SCLK,
 input F_MOSI,
 input ICE_CS,
 output PHV,
 output PnHV,
 output Pdamp,
 output ADC_CLK,
 output DAC_SCLK,
 output DAC_CS,
 output DAC_MOSI,
 output F_MISO,
 output Lred,
 output Lgreen,
 output Lblue
);
 
 // @include adc_dac_pulser_top.v
 // @include up5kPLL.v
 // @include mcp4812.v
 // @include spi_slave.v
 
 //F_SCLK, F_MOSI, F_MISO pin assignments are nmanually edited !!!
 
 adc_dac_pulser_top pulsar_uut(
 RCLK,
 BT_USER,
 BT_TRIG,
 DCLK,
 ADC_DATA,
 HILO,
 HV_EN,
 TOP_T1,
 TOP_T2,
 F_SCLK,
 F_MOSI,
 ICE_CS,
 PHV,
 PnHV,
 Pdamp,
 ADC_CLK,
 DAC_SCLK,
 DAC_CS,
 DAC_MOSI,
 F_MISO,
 Lred,
 Lgreen,
 Lblue);
 
endmodule
